# ==========================================
# Resume A4 Theme Configuration
# ==========================================
# Complete configuration guide: https://github.com/mertbakir/resume-a4

# Basic Hugo Configuration
baseURL: /                  # https://mertbakir.gitlab.io/resume
title: YOUR NAME | Resume   # Title of the web page
languageCode: en-us
disableKinds: [taxonomy, term, page, section, RSS, sitemap, robotsTXT, '404']
theme: resume-a4

# ==========================================
# QUICK START GUIDE
# ==========================================
# 1. Replace "YOUR NAME" above with your actual name
# 2. Update the data files in the /data folder with your information
# 3. Customize the sections below to match your needs
# 4. Run `hugo server` to preview your resume

# ==========================================
# THEME ARCHITECTURE
# ==========================================
# The theme constructs main column, side column and additional pages from features.
# Every column and page may include any features.
# Specialized templates: about, education, experience, publications, languages. 
#   Other features (sections) are considered as user-defined-feature (e.g. skills, projects, certificates)
#   and only those user-defined ones support widgets. Widgets determine how the content is rendered.
# Available widgets: details-list (default), word-list  
# 
# For detailed configuration guide see: CONFIGURATION.md
#
# ==========================================
# DATA FILES
# ==========================================
# Your resume content is stored in YAML files in the /data folder:
#   - features.yaml     → Contact info, and other user defined sections
#   - experience.yaml   → Work experience and career history
#   - education.yaml    → Academic background and degrees
#   - projects.yaml     → Personal and professional projects
#   - publications.yaml → Academic publications and papers

# ==========================================
# THEME CONFIGURATION
# ==========================================

params:
  # ========================================
  # Global Settings
  # ========================================
  useFontAwesome: true          # Enable Font Awesome icons throughout the theme
  externalLinkIcon: true        # Show icons for external links
  
  # Custom CSS Files (optional)
  # css:
  # - custom.scss               # Your custom styles - copy assets/ folder from exampleSite to customize
  # - print_urls.scss           # Uncomment to show URLs when printing
  
  # ========================================
  # Header Configuration
  # ========================================
  header:
    useFontAwesome: true        # Enable icons in header
    contactOnSide: false        # true = contact info on right side (ignored if avatar is enabled)
    avatar: false               # Set to filename (e.g., "avatar.jpg") to show profile picture from /static folder
    contact: true               # Show contact information in header
    tagline: true               # Show professional tagline/summary
    links: false                # Show social/professional links in header
  # ========================================
  # PAGE LAYOUT CONFIGURATION
  # ========================================
  # Design your resume layout with multiple pages and flexible sections
  
  pages:
    # ========================================
    # PAGE 1: Main Resume Page
    # ========================================
    - header: true                  # Show header with name, contact info, etc.
      
      # SIDE COLUMN SECTIONS
      side:                         # Two column layout can be disabled, by setting this to false.
      - feature: education          # Education history from data/education.yaml
      - feature: languages          # Language skills from data/features.yaml
      - feature: skills             # Technical skills  
        title: Technical Skills     # Custom section title (overrides default)
        widget: word-list           # How to display: word-list widget
        style: compact              # Style: list, compact, or title-list
        
      - feature: interests          # Personal interests
        widget: word-list           # Display as word list
        style: list                 # Style: bulleted list format
        
      # MAIN CONTENT SECTIONS (LEFT COLUMN)
      features:
        - feature: about            # Professional summary/about section
          title: About Me           # Section title
          
        - feature: experience       # Work experience from data/experience.yaml

    # ========================================  
    # PAGE 2: Additional Information (Optional)
    # ========================================
    - header: true                  # Repeat header on second page
      side: false                   # Show sidebar on second page
      
      features:
        - feature: experience
          title: Experience (Cont.) # Continue experience from page 1
          
        - feature: projects         # Projects from data/projects.yaml
          collection: projects      # Specify data source (defaults to feature name)
          
        - feature: publications     # Academic publications
          title: Academic Studies   # Rename section title
          style: IEEE               # Style: IEEE, APA, or TitleFirst[.Bold][.Author][.MultiLine]
                                    #   keys within brackets are optional. 
                                    #   Example: TitleFirst, TitleFirst.Bold, TitleFirst.MultiLine, TitleFirst.Bold.Author.MultiLine
    - header: true
      side: false
      features:
        - feature: awards           # Awards and honors
        
        - feature: certificates     # Professional certifications  
          title: Certifications     # Custom section title
          
        - feature: interests        # You can repeat a section.
          widget: word-list
          style: list
  # ========================================
  # SECTION-SPECIFIC SETTINGS
  # ========================================
  
  # Experience Section Settings
  experience:
    grouped: false              # false = chronological, true = group by company
    tools: 
      show: false               # Show technology tags for each role
      title: Technologies       # Title for technology tags
      
  # Education Section Settings  
  education:
    useFontAwesome: true        # Show icons for education entries
    externalLinkIcon: false     # Hide external link icons
    location:
      show: false               # Show/hide location information
    details:
      show: false               # Show/hide detailed descriptions
    namePrimary: false          # true = institution first, false = degree first
    
  # Publications Section Settings
  publications:
    useFontAwesome: false       # Disable icons for publications
    externalLinkIcon: false     # Hide external link icons
    
  # General Item Title Settings
  itemTitle:
    useFontAwesome: false       # Icons for item titles
    externalLinkIcon: false     # External link icons for titles
        
  # ========================================
  # FOOTER CONFIGURATION
  # ========================================
  footer:
    show: true                  # Display footer on all pages
    credits: true               # Show theme credits
    footnote: >-                # Custom footer text (supports markdown)
      You can print this resume in A4 size or save as PDF. | Updated at 2025-08-26.
      
    # Footer Links (social media, websites, etc.)
    links:
      - prefix: Contact me on   # Text before link
        title: LinkedIn         # Link text
        url: 'https://linkedin.com/in/yourprofile/'  # Replace with your LinkedIn URL
        icon: fab fa-linkedin   # Font Awesome icon
        
      - prefix: Check out my    # Text before link  
        title: Website          # Link text
        url: 'https://yourwebsite.com/'              # Replace with your website URL
        icon: fas fa-globe      # Font Awesome icon

